server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置FEIG客户端超时时间(openfeign默认支持ribbon)
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000